version: "3.7"

services:
  database: 
    image: postgres
    container_name: db_authentication_js
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: authentication_js
    ports:
      - 3300:3300
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata: