version: "3.7"

services:
  database: 
    image: postgres
    container_name: db_authentication_js
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: